# Generated by Django 4.2.3 on 2023-07-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='company_name',
            new_name='company',
        ),
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
        migrations.AlterModelTable(
            name='vacancy',
            table='vacancies',
        ),
    ]
