# Generated by Django 4.2.3 on 2023-07-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vacancy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='attachment',
            field=models.FileField(null=True, upload_to='vacancy/attachments/'),
        ),
    ]
